### ISSUE TITLE
`DetectMain` fails with recent Kotlin

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1020]
Our `DetectMain` fails when using with Kotlin 1.4.21 with:

```
Compiling failed with exitcode 1, compiler output:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/functions/Function1
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at DetectMain.main(DetectMain.java:41)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.functions.Function1
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more
```

for trivial programs.

This can be worked around by explicitly requiring an entry point, but we should also fix it to work without an entry point again. If we can't use reflection anymore, then we can at least make our best guess (capitalize filename, append `Kt`).
The current breakage is especially annoying when importing jury submissions which doesn't have a way to specify entry points as of now.

**Comment by nickygerritsen** [comment]
We now believe this was with a wrong compiler script which we now detect using hashes.
