### ISSUE TITLE
Setting REMOTE_USER results in ServiceNotFoundException: "security.authentication.listener.form.main"

### ISSUE THREAD

**Issue by ykazakov** [DOMjudge/domjudge#840]
### Description of the problem
I am trying to setup authentication using REMOTE_USER in Domjudge 7.2.1 (fresh install in ubuntu 20.04).
According to the [instructions](https://www.domjudge.org/docs/manual/7.2/config-advanced.html#using-remote-user), I have replaced the content of the main section of `webapp/config/packages/security.yaml` as follows:
```
        # rest of app does form_login
        main:
            pattern: ^/
            remote_user:
                provider: domjudge_db_provider
```
Then during the [installation](https://www.domjudge.org/docs/manual/7.2/install-domserver.html#installation) I obtain the following error when trying to setup the database:

```
ubuntu@domjudge1:~/domjudge-7.2.1$ sudo /opt/domjudge/domserver/bin/dj_setup_database install
Database credentials read from '/opt/domjudge/domserver/etc/dbpasswords.secret'.
DOMjudge database and user(s) created.

In ContainerBuilder.php line 1024:
                                                                                           
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]               
  You have requested a non-existent service "security.authentication.listener.form.main".  
                                                                                           

Exception trace:
  at /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/ContainerBuilder.php:1024
 Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at /opt/domjudge/domserver/webapp/src/DependencyInjection/Compiler/ChangeMainFormAuthenticationListenerPass.php:21
 App\DependencyInjection\Compiler\ChangeMainFormAuthenticationListenerPass->process() at /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/Compiler/Compiler.php:94
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/ContainerBuilder.php:753
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /opt/domjudge/domserver/lib/vendor/symfony/http-kernel/Kernel.php:556
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /opt/domjudge/domserver/lib/vendor/symfony/http-kernel/Kernel.php:133
 Symfony\Component\HttpKernel\Kernel->boot() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:159
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:65
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /opt/domjudge/domserver/webapp/bin/console:42
```

### Your environment
- domjudge 7.2.1 (installation from sources)
- ubuntu 20.04 (running inside an lxd container)
- apache v. 2.4.41-4ubuntu3

### Steps to reproduce
```
$ # create a fresh lxd container based on ubuntu 20.04 
$ # (should also work if run directly on ubuntu 20.04, but I did not test it)
$ lxc launch ubuntu:focal domjudge1
$ # enter the container under the user ubuntu
$ lxc exec domjudge1 -- su ubuntu -l
$ # download and unpack domjudge
$ wget https://www.domjudge.org/releases/domjudge-7.2.1.tar.gz
$ tar xzf domjudge-7.2.1.tar.gz
$ cd domjudge-7.2.1/
$ # install required packages
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install zip unzip mariadb-server apache2 php php-fpm php-cli php-gd php-curl php-mysql php-json php-xml php-intl php-mbstring php-zip composer ntp build-essential libcgroup-dev libcurl4-nss-dev  libjsoncpp-dev
$ # setup REMOTE_USER according to the instructions
$ vi webapp/config/packages/security.yaml
$ cat webapp/config/packages/security.yaml
# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_JURY: [ROLE_BALLOON, ROLE_API, ROLE_API_READER, ROLE_API_SOURCE_READER]
        ROLE_ADMIN: [ROLE_JURY, ROLE_API, ROLE_JUDGEHOST, ROLE_API_READER, ROLE_API_WRITER, ROLE_API_SOURCE_READER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 10
    providers:
        domjudge_db_provider:
            entity:
                class: App\Entity\User
                property: username


    firewalls:
        # NOTE: If you change anything in this section, or move the guard authenticators around
        # NOTE: make sure to update the $stateless_fw_contexts variables in each guard authenticator
        # NOTE: Otherwise they may not be enabled.

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # SEE NOTE ABOVE IF CHANGING ANYTHING IN THIS SECTION
        # API does Basic Auth and IP address auth
        api:
            pattern: ^/api
            provider: domjudge_db_provider
            stateless: true
            user_checker: App\Security\UserChecker
            anonymous: ~
            guard:
                # SEE NOTE ABOVE IF CHANGING ANYTHING HERE
                authenticators:
                    - App\Security\DOMJudgeIPAuthenticator
                    - App\Security\DOMJudgeBasicAuthenticator
                entry_point: App\Security\DOMJudgeIPAuthenticator

        # rest of app does form_login
        main:
            pattern: ^/
            remote_user:
                provider: domjudge_db_provider

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
$ # run installation instructions
$ ./configure 
$ make build
$ sudo make install-domserver
$ /opt/domjudge/domserver/bin/dj_setup_database genpass
$ sudo /opt/domjudge/domserver/bin/dj_setup_database install # <- ERROR HERE
```

### Expected behaviour
Should be no errors

### Actual behaviour
```
Database credentials read from '/opt/domjudge/domserver/etc/dbpasswords.secret'.
DOMjudge database and user(s) created.

In ContainerBuilder.php line 1024:
                                                                                           
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]               
  You have requested a non-existent service "security.authentication.listener.form.main".  
                                                                                           

Exception trace:
  at /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/ContainerBuilder.php:1024
 Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at /opt/domjudge/domserver/webapp/src/DependencyInjection/Compiler/ChangeMainFormAuthenticationListenerPass.php:21
 App\DependencyInjection\Compiler\ChangeMainFormAuthenticationListenerPass->process() at /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/Compiler/Compiler.php:94
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/ContainerBuilder.php:753
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /opt/domjudge/domserver/lib/vendor/symfony/http-kernel/Kernel.php:556
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /opt/domjudge/domserver/lib/vendor/symfony/http-kernel/Kernel.php:133
 Symfony\Component\HttpKernel\Kernel->boot() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:159
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /opt/domjudge/domserver/lib/vendor/symfony/framework-bundle/Console/Application.php:65
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/domjudge/domserver/lib/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /opt/domjudge/domserver/webapp/bin/console:42
```

### Any other information that you want to share?

If I do not modify `webapp/config/packages/security.yaml` then Domjudge installs fine.
Then I tried enable REMOTE_USER *after* the installation, which gave a similar error:

1. Install Domjudge according to the [installation instructions](https://www.domjudge.org/docs/manual/7.2/install-domserver.html#installation)
1. Modify `webapp/config/packages/security.yaml` similarly as above
1. Run  `sudo make install-domserver`
1. Delete the cache directory `/opt/domjudge/domserver/webapp/var/cache/prod/`
(without deleting cache nothing seem to change)
1. Restart apache: `sudo systemctl restart apache2`
1. Access domjudge web interface from a browser => the page looks blank
1. Look into `/var/log/apache2/error.log` on the server:
```
PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: You have requested a non-existent service "security.authentication.listener.form.main". in /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/ContainerBuilder.php:1024\nStack trace:\n#0 /opt/domjudge/domserver/webapp/src/DependencyInjection/Compiler/ChangeMainFormAuthenticationListenerPass.php(21): Symfony\\Component\\DependencyInjection\\ContainerBuilder->getDefinition()\n#1 /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): App\\DependencyInjection\\Compiler\\ChangeMainFormAuthenticationListenerPass->process()\n#2 /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/ContainerBuilder.php(753): Symfony\\Component\\DependencyInjection\\Compiler\\Compiler->compile()\n#3 /opt/domjudge/domserver/lib/vendor/symfony/http-kernel/Kernel.php(556): Symfony\\Component\\DependencyInjection\\ContainerBuilder->compile()\n#4 /opt/domjudge/domserver/lib/vendor/symfony/http-kernel/Kernel.php(133): Sy in /opt/domjudge/domserver/lib/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1024, referer: https://domjudge-server/domjudge/jury/users/3
```

**Comment by ykazakov** [comment]
I do not know if it is related, but I wanted to [print all symfony services](https://symfony.com/doc/current/service_container/debug.html) of the default domjudge installation (without changing `security.yaml`), and I get some errors:

```
$ sudo /opt/domjudge/domserver/webapp/bin/console debug:container
08:26:36 ERROR     [console] Error thrown while running command "debug:container". Message: "The guard authentication provider cannot use the "App\Security\DOMJudgeIPAuthenticator" entry_point because another entry point is already configured by another provider! Either remove the other provider or move the entry_point configuration as a root key under your firewall (i.e. at the same level as "guard")." ["exception" => LogicException { …},"command" => "debug:container","message" => "The guard authentication provider cannot use the "App\Security\DOMJudgeIPAuthenticator" entry_point because another entry point is already configured by another provider! Either remove the other provider or move the entry_point configuration as a root key under your firewall (i.e. at the same level as "guard")."]

In GuardAuthenticationFactory.php line 100:
                                                                                                                                                                                                                                             
  The guard authentication provider cannot use the "App\Security\DOMJudgeIPAuthenticator" entry_point because another entry point is already configured by another provider! Either remove the other provider or move the entry_point confi  
  guration as a root key under your firewall (i.e. at the same level as "guard").                                                                                                                                                            
                                                                                                                                                                                                                                             

debug:container [--show-private] [--show-arguments] [--show-hidden] [--tag TAG] [--tags] [--parameter PARAMETER] [--parameters] [--types] [--env-var ENV-VAR] [--env-vars] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]
```

**Comment by ykazakov** [comment]
It seems that the [documentation](https://www.domjudge.org/docs/manual/7.2/config-advanced.html#using-remote-user) is a slightly misleading: probably one should not *remove* the stuff under `main` section, just *add* the setting for `remote_user`.

To fix the error reported for `debug:container`, upon the suggestion in the message, I have now moved `entry_point` to the same level as `guard`. So the following settings in `security.yml` now work for me to successfully login with `REMOTE_USER`:

```
    firewalls:
        # NOTE: If you change anything in this section, or move the guard authenticators around
        # NOTE: make sure to update the $stateless_fw_contexts variables in each guard authenticator
        # NOTE: Otherwise they may not be enabled.

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # SEE NOTE ABOVE IF CHANGING ANYTHING IN THIS SECTION
        # API does Basic Auth and IP address auth
        api:
            pattern: ^/api
            provider: domjudge_db_provider
            stateless: true
            user_checker: App\Security\UserChecker
            anonymous: ~
            guard:
                # SEE NOTE ABOVE IF CHANGING ANYTHING HERE
                authenticators:
                    - App\Security\DOMJudgeIPAuthenticator
                    - App\Security\DOMJudgeBasicAuthenticator
            entry_point: App\Security\DOMJudgeIPAuthenticator

        # rest of app does form_login
        main:
             pattern: ^/
             user_checker: App\Security\UserChecker
             guard:
                 authenticators:
                     - App\Security\DOMJudgeXHeadersAuthenticator
                     - App\Security\DOMJudgeIPAuthenticator
             entry_point: App\Security\DOMJudgeXHeadersAuthenticator
             anonymous: ~
             form_login:
                 login_path: login
                 check_path: login
                 csrf_token_generator: security.csrf.token_manager
                 use_referer: true
             remote_user:
                provider: domjudge_db_provider

             logout:
                 path:   logout
                 target: /public
```

**Comment by thijskh** [comment]
Thanks for the report and research. I agree that the documentation is wrong (or is now wrong for our current Symfony version?) re using REMOTE_USER. I will change it.

I cannot reproduce the issue you have which required you to move entry_point around. Running `php bin/console debug:container` from `webapp/` gives no errors for me.

**Comment by thijskh** [comment]
I've closed the issue now, if any issue remains with the debug:container command then it's probably better to file a new one. Thanks again for reporting.

**Comment by ykazakov** [comment]
@thijskh I see. I did not run the console command from the `webapp` directory. That appears the problem. When I do this, no error is reported. Sorry for the noise.
